# R code generated by weaver 
# from /Users/hadley/Documents/reshape/reshape/inst/doc/introductionw.wvr on 2006-02-27 
# ---------------------------------------------------------
weaver.width <- 6
weaver.height <- 4
setwd("/Users/hadley/Documents/reshape/reshape/inst/doc")
if (file.exists(".introductionw.wcache/cache.rdata")) load(".introductionw.wcache/cache.rdata")
library(xtable)	

##<Block:0x46d18c>
library(reshape); data(french_fries); options(digits=3)
save(list = ls(all=TRUE), file= ".introductionw.wcache/cache.rdata")
